## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df['STATUS'].nunique()

2

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(application_df.columns[[0, 1, 7, 9]], axis = 1)

application_df.head(20)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
5,T3,Independent,C1200,Preservation,Trust,0,5000,1
6,T3,Independent,C1000,Preservation,Trust,100000-499999,31452,1
7,T3,Independent,C2000,Preservation,Trust,10M-50M,7508025,1
8,T7,Independent,C1000,ProductDev,Trust,1-9999,94389,1
9,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
10,T3,Independent,C1200,Preservation,Trust,25000-99999,69656,0
11,T3,Independent,C2000,Preservation,Trust,100000-499999,165593,0
12,T3,CompanySponsored,C1200,Preservation,Association,0,5000,1
13,T3,Independent,C2700,Preservation,Trust,25000-99999,5301,1
14,T3,Independent,C1000,Preservation,Trust,0,5000,1
15,T3,Independent,C1200,Preservation,Trust,0,5000,1
16,T3,Independent,C2000,Preservation,Trust,0,5000,1
17,T3,Independent,C1000,Heathcare,Trust,50M+,86380556,0
18,T3,CompanySponsored,C1000,Preservation,Trust,0,5000,0
19,T3,CompanySponsored,C1000,Preservation,Trust,100000-499999,376109,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df.APPLICATION_TYPE.value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

# Below list uses cutoff value of value_counts <= 66:
application_types_to_replace = ["T13", "T12","T2", "T25", "T14", "T29", "T15", "T17"]

# application_types_to_replace
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classi_value_count = application_df.CLASSIFICATION.value_counts()
classi_value_count.head(50)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
C2190        1
C4200        1
C2600        1
C5200        1
C1370        1
Name: count, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classi_value_count = classi_value_count[classi_value_count <=800]
classi_value_count

CLASSIFICATION
C7000    777
C1700    287
C4000    194
C5000    116
C1270    114
        ...
C4120      1
C8210      1
C2561      1
C4500      1
C2150      1
Name: count, Length: 66, dtype: int64

In [9]:
# classifications_list = [item[0] for item in classi_value_count]
classifications_to_replace = classi_value_count.index.to_list()
classifications_to_replace

['C7000',
 'C1700',
 'C4000',
 'C5000',
 'C1270',
 'C2700',
 'C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
# why not correct: application_df['CLASSIFICATION'] = pd.get_dummies(application_df['CLASSIFICATION'])

In [12]:
application_df.to_csv("cleaned_application_df.csv", index=False)

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
application_df

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,108590,1,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,5000,0,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,6692,1,False,False,False,True,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,142590,1,False,False,False,True,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,0,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34295,5000,0,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34296,5000,0,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34297,5000,1,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
34298,36500179,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [15]:
# Split our preprocessed data into our features and target arrays
y = application_df.IS_SUCCESSFUL
X = application_df.drop(columns=['IS_SUCCESSFUL'])
# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1, stratify=y)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [26]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=6, activation ="relu", input_dim=X_train.shape[1]))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation ="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation ="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 6)                 252

 dense_10 (Dense)            (None, 16)                112

 dense_11 (Dense)            (None, 16)                272

 dense_12 (Dense)            (None, 1)                 17

=================================================================
Total params: 653 (2.55 KB)
Trainable params: 653 (2.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [27]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [28]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6232 - accuracy: 0.6720
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5699 - accuracy: 0.7268
Epoch 3/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5633 - accuracy: 0.7282
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5593 - accuracy: 0.7275
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5574 - accuracy: 0.7285
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5564 - accuracy: 0.7292
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5554 - accuracy: 0.7311
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5545 - accuracy: 0.7311
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5543 - accuracy: 0.7307
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5539 - accuracy: 0.7303
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5531 - accuracy: 0.7313
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5523 - accuracy: 0.7317
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7314
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5521 - accuracy: 0.7317
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7312
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5517 - accuracy: 0.7302
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5515 - accuracy: 0.7321
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5513 - accuracy: 0.7314
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5508 - accuracy: 0.7314
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5508 - accuracy: 0.7322
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5503 - accuracy: 0.7317
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5503 - accuracy: 0.7327
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5503 - accuracy: 0.7320
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7323
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7320
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7318
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7318
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7318
Epoch 29/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5493 - accuracy: 0.7320
Epoch 30/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5493 - accuracy: 0.7319
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7332
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7318
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7325
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7323
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5481 - accuracy: 0.7332
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5476 - accuracy: 0.7332
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5480 - accuracy: 0.7334
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5476 - accuracy: 0.7343
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7338
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7340
Epoch 41/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5472 - accuracy: 0.7337
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5473 - accuracy: 0.7341
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5474 - accuracy: 0.7339
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5472 - accuracy: 0.7339
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7336
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7338
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7340
Epoch 48/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5470 - accuracy: 0.7340
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5467 - accuracy: 0.7332
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7338
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5466 - accuracy: 0.7336
Epoch 52/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5465 - accuracy: 0.7336
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7342
Epoch 54/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5464 - accuracy: 0.7346
Epoch 55/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5462 - accuracy: 0.7334
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7322
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7336
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7344
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7331
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5463 - accuracy: 0.7335
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5461 - accuracy: 0.7336
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7337
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7336
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7341
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7337
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5459 - accuracy: 0.7337
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5459 - accuracy: 0.7334
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5456 - accuracy: 0.7339
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7349
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7340
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7336
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7341
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7332
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5457 - accuracy: 0.7336
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7343
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7332
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7338
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7337
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7338
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5455 - accuracy: 0.7344
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5453 - accuracy: 0.7348
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7335
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7341
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7345
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7348
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7335
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5452 - accuracy: 0.7347
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5452 - accuracy: 0.7343
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7341
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7335
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7336
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7339
Epoch 93/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5450 - accuracy: 0.7344
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5451 - accuracy: 0.7341
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7342
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7343
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7339
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7340
Epoch 99/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5449 - accuracy: 0.7337
Epoch 100/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5446 - accuracy: 0.7344

In [29]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5558 - accuracy: 0.7301 - 534ms/epoch - 2ms/step
Loss: 0.5557766556739807, Accuracy: 0.7301457524299622

In [30]:
# Export our model to HDF5 file
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import load_model


# Save the model to an HDF5 file
nn.save('Initial_model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

Model Optimization Process

In [31]:
!pip install keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.10/dist-packages (1.4.7)
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.2.2)

In [32]:
# Import our dependencies
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as skl
import tensorflow as tf

# Creating a DataFrame to plot the nonlinear dummy data
# Split our preprocessed data into our features and target arrays
y = application_df.IS_SUCCESSFUL
X = application_df.drop(columns=['IS_SUCCESSFUL'])
# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1, stratify=y)

# Use sklearn to split dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, random_state=78)

# Create scaler instance
X_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [33]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=5), activation=activation, input_dim=44))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=5),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn_model

In [34]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2,
    overwrite = True
    )

In [35]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=500,validation_data=(X_test_scaled,y_test))

Trial 2 Complete [00h 00m 01s]

Best val_accuracy So Far: None
Total elapsed time: 00h 00m 58s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
tanh              |sigmoid           |activation
1                 |6                 |first_units
1                 |2                 |num_layers
1                 |1                 |units_0
1                 |1                 |units_1
6                 |None              |units_2
1                 |None              |units_3
3                 |3                 |tuner/epochs
0                 |0                 |tuner/initial_epoch
2                 |2                 |tuner/bracket
0                 |0                 |tuner/round

Epoch 1/3

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/tuners/hyperband.py", line 427, in run_trial
    return super().run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 233, in _build_and_fit_model
    results = self.hypermodel.fit(hp, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/hypermodel.py", line 149, in fit
    return model.fit(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filegfemu5s7.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1150, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 44), found shape=(None, 41)

RuntimeError: Number of consecutive failures exceeded the limit of 3.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/tuners/hyperband.py", line 427, in run_trial
    return super().run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 233, in _build_and_fit_model
    results = self.hypermodel.fit(hp, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/hypermodel.py", line 149, in fit
    return model.fit(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filegfemu5s7.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1150, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 44), found shape=(None, 41)

In [ ]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import load_model


# Save the model to an HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')